// Top-level build file where you can add configuration options common to all sub-projects/modules.
import org.gradle.api.tasks.compile.JavaCompile

plugins {
    // Plugins automatically generated by TLGradle.kt
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.ksp) apply false
}

subprojects {
    tasks.withType<JavaCompile>().configureEach {
        options.compilerArgs.add("-Xlint:none")
    }
}

tasks.register<Delete>("clean") {
    delete(rootProject.layout.buildDirectory)
}