/* DO NOT EDIT THIS FILE - it is machine generated (Manually recreated for migration) */
/**
 * @author android_zero
 * @brief JNI 动态注册聚合头文件。
 * 负责包含所有具体语言的头文件，并提供宏来统一定义方法数组和执行注册。
 */

#include <jni.h>
#include "ts__log.h"

#ifndef __TS_LOG_DEBUG
#ifdef NDEBUG
#define __TS_LOG_DEBUG 0
#else
#define __TS_LOG_DEBUG 1
#endif
#endif

// Include generated headers for all grammars (Currently only cpp)
#include "ts_cpp.h"


#ifndef _Included__TS_JNI_ONLOAD_
#define _Included__TS_JNI_ONLOAD_

// 自动注册宏：在 JNI_OnLoad 中调用，注册所有包含的语言
#define TS_JNI_ONLOAD__AUTO_REGISTER(env) \
    TSLanguageCpp_Native_AutoRegisterNatives(env); \

// 定义方法数组宏：实例化 JNINativeMethod 数组
#define TS_JNI_ONLOAD__DEFINE_METHODS_ARR \
    TSLanguageCpp_Native_DefMethodsArray; \

#endif