package com.xc.code.ui.theme

import androidx.compose.ui.graphics.Color

// ── 基础色板（唯一值） ──────────────────────────────────
private data class base_colors(
    // 页面 & 表面
    val bg: Color,
    val surface: Color,
    val surface_variant: Color,
    val surface_pressed: Color,
    // 文字
    val text_primary: Color,
    val text_secondary: Color,
    val text_dim: Color,
    val text_dialog: Color,
    val text_hint: Color,
    // 强调色
    val accent: Color,
    val accent_light: Color,
    val accent_bg: Color,
    val accent_bg_strong: Color,
    // 弹窗
    val dialog_clone_text: Color,
    // 渐变（首页用）
    val gradient_start: Color,
    val gradient_middle: Color,
    val gradient_end: Color,
    // 按钮 & 图标
    val button_bg: Color,
    val logo_tint: Color,
    val card_chevron: Color,
    // 胶囊控件
    val capsule_bg: Color,
    val capsule_icon: Color,
    val capsule_divider: Color,
    // 输出面板
    val output_panel_bg: Color,
    val output_capsule_bg: Color,
    // 文件树
    val file_tree_folder_icon: Color,
    val file_tree_action_icon: Color,
    // 分隔线
    val divider: Color,
    val divider_dim: Color,
    // 标签栏
    val tab_separator: Color,
    val tab_unselected_bg: Color,
    val tab_unselected_content: Color,
    val tab_add_icon: Color,
    val tab_selected_text: Color,
    // 按键
    val key_button_pressed_bg: Color,
    val key_button_pressed_text: Color,
    // 终端
    val terminal_cursor: Int,
    val terminal_foreground: Int,
    val terminal_background: Int,
    // 面板覆盖
    val panel_overlay: Color,
    // 状态色
    val danger: Color,
    val danger_bg: Color,
    val success: Color,
    val success_bg: Color,
    val warning: Color,
    val warning_bg: Color,
)

// ── 深色基础色板 ────────────────────────────────────────
private val dark_base = base_colors(
    bg = Color(0xFF11131C),
    surface = Color(0xFF1F2230),
    surface_variant = Color(0xFF2A2A3A),
    surface_pressed = Color(0xFF323446),
    text_primary = Color(0xFFE8E8F8),
    text_secondary = Color(0xFF707486),
    text_dim = Color(0xFF88889C),
    text_dialog = Color(0xFFE1E1EF),
    text_hint = Color(0xFF787C8C),
    accent = Color(0xFFC0CCFF),
    accent_light = Color(0xFFB6C4FF),
    accent_bg = Color(0x29C0CCFF),
    accent_bg_strong = Color(0x26C0CCFF),
    dialog_clone_text = Color(0xFF1A1A2E),
    gradient_start = Color(0xFF0B2058),
    gradient_middle = Color(0xFF121A33),
    gradient_end = Color(0xFF141622),
    button_bg = Color(0x15FFFFFF),
    logo_tint = Color(0xFFF5F5FF),
    card_chevron = Color(0xFF444556),
    capsule_bg = Color(0xFF191B24),
    capsule_icon = Color(0xFFDDE1EC),
    capsule_divider = Color(0xFF343747),
    output_panel_bg = Color(0xFF11131C),
    output_capsule_bg = Color(0xFF191B24),
    file_tree_folder_icon = Color(0xFF8EA2FF),
    file_tree_action_icon = Color(0xFF8EA2FF),
    divider = Color(0x4D787C8C),
    divider_dim = Color(0x2E787C8C),
    tab_separator = Color(0x2EFFFFFF),
    tab_unselected_bg = Color(0x1FFFFFFF),
    tab_unselected_content = Color(0xFFB0B0BE),
    tab_add_icon = Color(0xFFFFFFFF),
    tab_selected_text = Color(0xFFFFFFFF),
    key_button_pressed_bg = Color(0xFF3A3A4A),
    key_button_pressed_text = Color(0xFFFFFFFF),
    terminal_cursor = 0xFFB6C4FF.toInt(),
    terminal_foreground = 0xFFFFFFFF.toInt(),
    terminal_background = 0xFF11131C.toInt(),
    panel_overlay = Color(0xD111131C),
    danger = Color(0xFFFF5F57),
    danger_bg = Color(0x29FF5F57),
    success = Color(0xFF35D07F),
    success_bg = Color(0x2935D07F),
    warning = Color(0xFFFFBD2E),
    warning_bg = Color(0x29FFBD2E),
)

// ── 浅色基础色板 ────────────────────────────────────────
private val light_base = base_colors(
    bg = Color(0xFFFAF8FF),
    surface = Color(0xFFF1F0FA),
    surface_variant = Color(0xFFE8E8F4),
    surface_pressed = Color(0xFFE2E2F0),
    text_primary = Color(0xFF2D2D3F),
    text_secondary = Color(0xFF7A7A8C),
    text_dim = Color(0xFF666678),
    text_dialog = Color(0xFF333333),
    text_hint = Color(0xFF888888),
    accent = Color(0xFF1F54E8),
    accent_light = Color(0xFF004DEA),
    accent_bg = Color(0x1F1F54E8),
    accent_bg_strong = Color(0x261F54E8),
    dialog_clone_text = Color(0xFFFFFFFF),
    gradient_start = Color(0xFFEBEDFF),
    gradient_middle = Color(0xFFF2F1FF),
    gradient_end = Color(0xFFFAF8FF),
    button_bg = Color(0x15000000),
    logo_tint = Color(0xFF2D2D3F),
    card_chevron = Color(0xFFB0B0C2),
    capsule_bg = Color(0xFFF4F3FF),
    capsule_icon = Color(0xFF202231),
    capsule_divider = Color(0xFFDCD9E8),
    output_panel_bg = Color(0xFFFAF8FF),
    output_capsule_bg = Color(0xFFF4F3FF),
    file_tree_folder_icon = Color(0xFF1F54E8),
    file_tree_action_icon = Color(0xFF1F54E8),
    divider = Color(0x4D888888),
    divider_dim = Color(0x2E888888),
    tab_separator = Color(0xFFD8D5E0),
    tab_unselected_bg = Color(0xFFF1EFF6),
    tab_unselected_content = Color(0xFF4A4A4A),
    tab_add_icon = Color(0xFF000000),
    tab_selected_text = Color(0xFF000000),
    key_button_pressed_bg = Color(0xFFEEEEEE),
    key_button_pressed_text = Color(0xFF000000),
    terminal_cursor = 0xFF004DEA.toInt(),
    terminal_foreground = 0xFF1A1A28.toInt(),
    terminal_background = 0xFFFAF8FF.toInt(),
    panel_overlay = Color(0xD1FFFFFF),
    danger = Color(0xFFE5484D),
    danger_bg = Color(0x1FE5484D),
    success = Color(0xFF168A4A),
    success_bg = Color(0x1F168A4A),
    warning = Color(0xFFB7791F),
    warning_bg = Color(0x1FB7791F),
)

// ── 辅助：从 base 构建 app_colors ──────────────────────────
private fun base_colors.to_app_colors() = app_colors(
    gradient_start = gradient_start,
    gradient_middle = gradient_middle,
    gradient_end = gradient_end,
    title_large = text_primary,
    title_highlight = accent,
    subtitle = text_secondary,
    section_title = text_primary,
    card_bg = surface,
    card_pressed = surface_pressed,
    card_text_title = text_primary,
    card_text_subtitle = text_dim,
    card_icon_bg = accent,
    card_chevron = card_chevron,
    logo_tint = logo_tint,
    top_button_bg = button_bg,
    top_button_icon = text_primary,
    search_button_active = accent,
    search_button_bg_active = accent_bg_strong,
    input_hint = text_secondary,
    input_text = text_primary,
    input_border = accent,
    dialog_bg = bg,
    dialog_text = text_dialog,
    dialog_hint = text_hint,
    dialog_icon = accent,
    dialog_cancel = accent,
    dialog_clone_bg = accent,
    dialog_clone_text = dialog_clone_text,
    dialog_card_bg = surface_variant,
    dialog_input_bg = bg,
    dialog_input_text = text_dialog,
    dialog_input_hint = text_hint,
    dialog_input_border = accent_light,
    dialog_input_icon = accent_light,
    dialog_input_icon_hint = text_hint,
    danger = danger,
    danger_bg = danger_bg,
    success = success,
    success_bg = success_bg,
    warning = warning,
    warning_bg = warning_bg,
    info = accent,
    info_bg = accent_bg,
    terminal_cursor = terminal_cursor,
    terminal_foreground = terminal_foreground,
    terminal_background = terminal_background,
    key_button_pressed_bg = key_button_pressed_bg,
    key_button_pressed_text = key_button_pressed_text,
    key_button_normal_text = text_dim,
    key_button_active_text = accent,
    terminal_tab_add_icon = tab_add_icon,
    terminal_tab_separator = tab_separator,
    terminal_tab_selected_bg = Color.Transparent,
    terminal_tab_unselected_bg = tab_unselected_bg,
    terminal_tab_selected_icon = accent,
    terminal_tab_selected_text = tab_selected_text,
    terminal_tab_unselected_content = tab_unselected_content,
    editor_bg = bg,
    editor_text = text_dialog,
    editor_hint = text_hint,
    editor_icon = accent,
    editor_toolbar_icon = text_primary,
    editor_panel_overlay = panel_overlay,
    editor_button_bg = button_bg,
    editor_capsule_bg = capsule_bg,
    editor_capsule_icon = capsule_icon,
    editor_capsule_divider = capsule_divider,
    editor_output_panel_bg = output_panel_bg,
    editor_output_capsule_bg = output_capsule_bg,
    editor_file_tree_folder_icon = file_tree_folder_icon,
    editor_file_tree_action_icon = file_tree_action_icon,
    editor_browse_files_button_bg = file_tree_action_icon,
    editor_browse_files_button_content = dialog_clone_text,
    editor_text_action_bg = surface_variant,
    editor_text_action_divider = key_button_pressed_bg,
    editor_text_action_content = text_primary,
    editor_tab_add_icon = tab_add_icon,
    editor_tab_separator = tab_separator,
    editor_tab_selected_bg = Color.Transparent,
    editor_tab_unselected_bg = tab_unselected_bg,
    editor_tab_selected_icon = accent,
    editor_tab_selected_text = tab_selected_text,
    editor_tab_unselected_content = tab_unselected_content,
    editor_sidebar_selected_bg = accent_bg,
    editor_divider = divider,
    editor_line_divider = divider_dim,
)

// ── 对外暴露（向下兼容） ──────────────────────────────────
data class app_colors(
    val gradient_start: Color,
    val gradient_middle: Color,
    val gradient_end: Color,
    val title_large: Color,
    val title_highlight: Color,
    val subtitle: Color,
    val section_title: Color,
    val card_bg: Color,
    val card_pressed: Color,
    val card_text_title: Color,
    val card_text_subtitle: Color,
    val card_icon_bg: Color,
    val card_chevron: Color,
    val logo_tint: Color,
    val top_button_bg: Color,
    val top_button_icon: Color,
    val search_button_active: Color,
    val search_button_bg_active: Color,
    val input_hint: Color,
    val input_text: Color,
    val input_border: Color,
    val dialog_bg: Color,
    val dialog_text: Color,
    val dialog_hint: Color,
    val dialog_icon: Color,
    val dialog_cancel: Color,
    val dialog_clone_bg: Color,
    val dialog_clone_text: Color,
    val dialog_card_bg: Color,
    val dialog_input_bg: Color,
    val dialog_input_text: Color,
    val dialog_input_hint: Color,
    val dialog_input_border: Color,
    val dialog_input_icon: Color,
    val dialog_input_icon_hint: Color,
    val danger: Color,
    val danger_bg: Color,
    val success: Color,
    val success_bg: Color,
    val warning: Color,
    val warning_bg: Color,
    val info: Color,
    val info_bg: Color,
    val terminal_cursor: Int,
    val terminal_foreground: Int,
    val terminal_background: Int,
    val key_button_pressed_bg: Color,
    val key_button_pressed_text: Color,
    val key_button_normal_text: Color,
    val key_button_active_text: Color,
    val terminal_tab_add_icon: Color,
    val terminal_tab_separator: Color,
    val terminal_tab_selected_bg: Color,
    val terminal_tab_unselected_bg: Color,
    val terminal_tab_selected_icon: Color,
    val terminal_tab_selected_text: Color,
    val terminal_tab_unselected_content: Color,
    val editor_bg: Color,
    val editor_text: Color,
    val editor_hint: Color,
    val editor_icon: Color,
    val editor_toolbar_icon: Color,
    val editor_panel_overlay: Color,
    val editor_button_bg: Color,
    val editor_capsule_bg: Color,
    val editor_capsule_icon: Color,
    val editor_capsule_divider: Color,
    val editor_output_panel_bg: Color,
    val editor_output_capsule_bg: Color,
    val editor_file_tree_folder_icon: Color,
    val editor_file_tree_action_icon: Color,
    val editor_browse_files_button_bg: Color,
    val editor_browse_files_button_content: Color,
    val editor_text_action_bg: Color,
    val editor_text_action_divider: Color,
    val editor_text_action_content: Color,
    val editor_tab_add_icon: Color,
    val editor_tab_separator: Color,
    val editor_tab_selected_bg: Color,
    val editor_tab_unselected_bg: Color,
    val editor_tab_selected_icon: Color,
    val editor_tab_selected_text: Color,
    val editor_tab_unselected_content: Color,
    val editor_sidebar_selected_bg: Color,
    val editor_divider: Color,
    val editor_line_divider: Color,
)

val dark_app_colors = dark_base.to_app_colors()
val light_app_colors = light_base.to_app_colors()
