package com.xc.code.toolchain.runtime

import java.io.File
import java.nio.file.Files

class rootfs_patcher {
    fun patch(
        paths: toolchain_runtime_paths,
        options: rootfs_patch_options = rootfs_patch_options()
    ) {
        val rootfs = paths.ubuntu_base_dir
        val etc_dir = File(rootfs, "etc")
        if (!etc_dir.isDirectory) return

        ensure_dns(etc_dir, options.nameservers)
        ensure_hosts(etc_dir, options.hostname)
        ensure_hostname(etc_dir, options.hostname)
        ensure_locale(etc_dir, options.locale)
        ensure_timezone(rootfs, etc_dir, options.timezone)
        ensure_groups(etc_dir, options.group_ids.ifEmpty { current_supplementary_group_ids() })
        ensure_temp_dirs(rootfs)
        ensure_home(paths.home_dir, rootfs)
    }

    private fun ensure_dns(etc_dir: File, nameservers: List<String>) {
        val resolv_conf = File(etc_dir, "resolv.conf")
        val should_write = when {
            Files.isSymbolicLink(resolv_conf.toPath()) -> true
            !resolv_conf.exists() -> true
            !resolv_conf.isFile -> true
            else -> resolv_conf.readText()
                .lineSequence()
                .filter { it.trimStart().startsWith("nameserver ") }
                .none { line ->
                    val server = line.trim().removePrefix("nameserver").trim()
                    server.isNotBlank() && server !in local_resolvers
                }
        }
        if (!should_write) return

        if (resolv_conf.exists() || Files.isSymbolicLink(resolv_conf.toPath())) {
            resolv_conf.delete()
        }

        val servers = nameservers
            .filter { it.isNotBlank() }
            .distinct()
            .take(max_dns_servers)
            .ifEmpty { default_dns_servers }

        resolv_conf.writeText(
            buildString {
                appendLine("# Generated by XCode toolchain runtime.")
                servers.forEach { appendLine("nameserver $it") }
                appendLine("options edns0 trust-ad")
            }
        )
    }

    private fun ensure_hosts(etc_dir: File, hostname: String) {
        val hosts = File(etc_dir, "hosts")
        val lines = if (hosts.isFile) hosts.readLines() else emptyList()
        val has_ipv4_localhost = lines.any { line ->
            val parts = line.substringBefore('#').trim().split(whitespace_regex)
            parts.firstOrNull() == "127.0.0.1" && "localhost" in parts.drop(1)
        }
        val has_ipv6_localhost = lines.any { line ->
            val parts = line.substringBefore('#').trim().split(whitespace_regex)
            parts.firstOrNull() == "::1" && "localhost" in parts.drop(1)
        }
        if (has_ipv4_localhost && has_ipv6_localhost) return

        hosts.parentFile?.mkdirs()
        hosts.appendText(
            buildString {
                if (hosts.exists() && hosts.length() > 0 && !hosts.readText().endsWith('\n')) appendLine()
                if (!has_ipv4_localhost) {
                    append("127.0.0.1 localhost")
                    if (hostname.isNotBlank() && hostname != "localhost") append(" $hostname")
                    appendLine()
                }
                if (!has_ipv6_localhost) {
                    appendLine("::1 localhost ip6-localhost ip6-loopback")
                }
            }
        )
    }

    private fun ensure_hostname(etc_dir: File, hostname: String) {
        val target = File(etc_dir, "hostname")
        if (target.isFile && target.readText().trim().isNotBlank()) return
        target.writeText("${hostname.ifBlank { default_hostname }}\n")
    }

    private fun ensure_locale(etc_dir: File, locale: String) {
        val default_dir = File(etc_dir, "default").apply { mkdirs() }
        val target = File(default_dir, "locale")
        val lines = if (target.isFile) target.readLines().toMutableList() else mutableListOf()
        if (lines.any { it.trim().startsWith("LANG=") }) return
        lines += "LANG=$locale"
        target.writeText(lines.joinToString(separator = "\n", postfix = "\n"))
    }

    private fun ensure_timezone(rootfs: File, etc_dir: File, timezone: String) {
        val timezone_file = File(etc_dir, "timezone")
        timezone_file.parentFile?.mkdirs()
        if (!timezone_file.isFile || timezone_file.readText().trim() != timezone) {
            timezone_file.writeText(timezone)
        }

        val zoneinfo = File(rootfs, "usr/share/zoneinfo/$timezone")
        val localtime = File(etc_dir, "localtime")
        if (zoneinfo.isFile) {
            if (localtime.exists() || Files.isSymbolicLink(localtime.toPath())) localtime.delete()
            runCatching { Files.createSymbolicLink(localtime.toPath(), File("/usr/share/zoneinfo/$timezone").toPath()) }
                .recoverCatching { zoneinfo.copyTo(localtime, overwrite = true) }
        }
    }

    private fun ensure_groups(etc_dir: File, group_ids: List<Long>) {
        val target = File(etc_dir, "group")
        if (!target.exists()) target.writeText("root:x:0:\n")
        val lines = target.readLines().toMutableList()
        val existing_ids = lines.mapNotNull { line -> line.split(':').getOrNull(2)?.toLongOrNull() }.toSet()
        val existing_names = lines.mapNotNull { line -> line.substringBefore(':').takeIf { it.isNotBlank() } }.toSet()
        val additions = group_ids
            .filter { it > 0 && it !in existing_ids }
            .distinct()
            .map { id ->
                val base_name = "android_gid_$id"
                val name = if (base_name in existing_names) "${base_name}_xcode" else base_name
                "$name:x:$id:"
            }
        if (additions.isEmpty()) return

        target.appendText(
            buildString {
                if (target.length() > 0 && !target.readText().endsWith('\n')) appendLine()
                additions.forEach { appendLine(it) }
            }
        )
    }

    private fun ensure_temp_dirs(rootfs: File) {
        listOf("tmp", "var/tmp", "root").forEach { path -> File(rootfs, path).mkdirs() }
        listOf(File(rootfs, "tmp"), File(rootfs, "var/tmp")).forEach { dir ->
            dir.setReadable(true, false)
            dir.setWritable(true, false)
            dir.setExecutable(true, false)
        }
        File(rootfs, "root").apply {
            setReadable(true, true)
            setWritable(true, true)
            setExecutable(true, true)
        }
    }

    private fun ensure_home(home_dir: File, rootfs: File) {
        home_dir.mkdirs()
        val root_dir = File(rootfs, "root")
        if (root_dir.isDirectory && home_dir.list()?.isEmpty() != false) {
            root_dir.copyRecursively(home_dir, overwrite = true)
        }
        ensure_bashrc(home_dir, rootfs)
        ensure_profile(home_dir, rootfs)
        home_dir.setReadable(true, false)
        home_dir.setWritable(true, true)
        home_dir.setExecutable(true, false)
    }

    private fun ensure_profile(home_dir: File, rootfs: File) {
        val profile = File(home_dir, ".profile")
        val source_profile = File(rootfs, "root/.profile")
        profile.parentFile?.mkdirs()
        if (!profile.exists()) {
            if (source_profile.isFile) {
                source_profile.copyTo(profile, overwrite = true)
            } else {
                profile.createNewFile()
            }
        }
    }

    private fun ensure_bashrc(home_dir: File, rootfs: File) {
        val bashrc = File(home_dir, ".bashrc")
        val source_bashrc = File(rootfs, "root/.bashrc")
        bashrc.parentFile?.mkdirs()
        if (!bashrc.exists() || !bashrc.readText().contains("XCode Terminal")) {
            if (source_bashrc.isFile) {
                source_bashrc.copyTo(bashrc, overwrite = true)
            } else if (!bashrc.exists()) {
                bashrc.createNewFile()
            }
        }

        val custom = """
        echo "Welcome To XCode Terminal"
        echo ""
        """.trimIndent()

        var content = bashrc.readText()
        if (!content.contains("XCode Terminal")) content += "\n$custom\n"
        content = content.replace("#force_color_prompt=yes", "force_color_prompt=yes")
        if (!content.contains("PROMPT_COMMAND")) {
            content = if (content.contains("HISTFILESIZE=2000")) {
                content.replace("HISTFILESIZE=2000", "HISTFILESIZE=2000\nPROMPT_COMMAND=\"history -a\"")
            } else {
                content + "\nPROMPT_COMMAND=\"history -a\"\n"
            }
        }
        bashrc.writeText(content)
    }

    private fun current_supplementary_group_ids(): List<Long> {
        val status = File("/proc/self/status")
        if (!status.isFile) return emptyList()
        val groups = status.readLines().firstOrNull { it.startsWith("Groups:") } ?: return emptyList()
        return groups
            .removePrefix("Groups:")
            .trim()
            .split(whitespace_regex)
            .mapNotNull { it.toLongOrNull() }
    }

    private companion object {
        private const val max_dns_servers = 3
        private const val default_hostname = "localhost"
        private val whitespace_regex = Regex("\\s+")
        private val local_resolvers = setOf("127.0.0.1", "127.0.0.53", "::1")
        private val default_dns_servers = listOf("1.1.1.1", "8.8.8.8", "223.5.5.5")
    }
}

data class rootfs_patch_options(
    val nameservers: List<String> = emptyList(),
    val hostname: String = "localhost",
    val locale: String = "C.UTF-8",
    val timezone: String = "Asia/Shanghai",
    val group_ids: List<Long> = emptyList()
)
